services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.3
    container_name: microservice_keycloak
    command: start-dev --import-realm

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    ports:
      - "8080:8080"

    volumes:
      - ./realm:/opt/keycloak/data/import

  db:
    image: postgres:17
    container_name: microservice_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productservice
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
